### ISSUE TITLE
Exclude argument when value is None

### ISSUE THREAD

**Issue by maresb** [mbdevpl/argunparse#1]
When I do `print(unparser.unparse_option('key',None))` I get `--key=None`, but I think the correct behavior should be to return the empty string.  Thanks for the nice package!

**Comment by mbdevpl** [comment]
I see... Well, this feature already works for False -- although I should've documented it.

```
In [1]: import argunparse

In [2]: print(argunparse.ArgumentUnparser().unparse_option('key', None))
--key=None

In [3]: print(argunparse.ArgumentUnparser().unparse_option('key', False))


In [4]:
```

I think it's not necessarily problem to treat None in the same way as False.

**Comment by mbdevpl** [comment]
New release coming soon.
